### ISSUE TITLE
Write Discussion Part

### ISSUE THREAD

**Issue by shaykhsiddique** [shaykhsiddique/Machine-Translation-with-RNN-Python#7]
In the discussion part, you have to directly interact with objectives. discuss about the objectives are filled up or not. 
- Discuss about the model design, why it's batter than traditional machine translation system.
![mainDiagram](https://user-images.githubusercontent.com/18369069/69717427-40b91900-1136-11ea-9642-c64c9bc1fa3b.jpg)

### and also this.

![context vector](https://user-images.githubusercontent.com/18369069/69717446-4878bd80-1136-11ea-8f6f-9e70bc0853b6.jpg)
- Discuss about **encoder-decoder** activation function. compare with this [article](https://towardsdatascience.com/applied-deep-learning-part-3-autoencoders-1c083af4d798). They used `relu` activation function and our research says `tanh` and `linear` are better for bangla natural language processing.
 - Discuss about loss and performance analysis **attention layer**. compare the model loss and accuracy with another paper. Link- [Bahdanau](https://arxiv.org/pdf/1409.0473.pdf)
> `accuracy = (100 - mean loss)`
- Discuss about why bangla language processing needs this types of research. find some online news article about important of bangla language processing and add that as reference. 
- Add some discussion conclusion line.

Upload your draft work here in the comment section.

**Comment by rifayetazamtalukder** [comment]
[Discussion and Iimitations.docx](https://github.com/shaykhsiddique/Machine-Translation-with-RNN-Python/files/3900233/Discussion.and.Iimitations.docx)

**Comment by shaykhsiddique** [comment]
> [Discussion and Iimitations.docx](https://github.com/shaykhsiddique/Machine-Translation-with-RNN-Python/files/3900233/Discussion.and.Iimitations.docx)

The article doesn't meet my requirements. @rifayetazamtalukder 
not good work.

**Comment by rifayetazamtalukder** [comment]
Here is another version. **add two more line for loss and accuracy. I'm stack here.**

[disscussion - v2.docx](https://github.com/shaykhsiddique/Machine-Translation-with-RNN-Python/files/3901964/disscussion.-.v2.docx)
